### ISSUE TITLE
Modificar imagen a un item existente usando restify

### ISSUE THREAD

**Issue by DeiverJC** [LuisHoyos7/inventy-api#35]
- Encontrar el endpoint para actualizar la imagen de un Item (producto)

**Comment by robim16** [comment]
Se agrega la funcionalidad para modificar la imagen de un item existente. Los cambios se realizaron en la rama del issue #31
porque los cambios hechos en aquella se veían afectados por este requerimiento y se debían reformular.


<img width="698" alt="image" src="https://github.com/user-attachments/assets/a848d7d0-dca4-4581-a690-3b5620ac117e">
<img width="698" alt="image" src="https://github.com/user-attachments/assets/a848d7d0-dca4-4581-a690-3b5620ac117e">
